CircleCI config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -43,8 +43,9 @@ jobs:
   deploy-github:
     <<: *defaults
     branches:
-      only:
-        - dev
+      ignore:
+        - master
+        - /feature.*/
     steps:
       - checkout
       - attach_workspace:
@@ -52,33 +53,23 @@ jobs:
       - deploy:
           name: Deploy to GitHub Pages
           command: |
-                npm run deploy
-              # set -e
-              # remote=$(git config remote.origin.url)
-              # if [ ! -d "build" ]
-              # then
-              #     echo "build folder not found"
-              #     exit 1
-              # fi
-              # mkdir gh-pages-branch
-              # cd gh-pages-branch
-              # git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
-              # git config --global user.name "$GH_NAME" > /dev/null 2>&1
-              # git init
-              # git remote add --fetch origin "$remote"
-              # if git rev-parse --verify origin/gh-pages > /dev/null 2>&1
-              # then
-              #     git checkout gh-pages
-              #     git rm -rf .
-              # else
-              #     git checkout --orphan gh-pages
-              # fi
-              # cp -a "../build/." .
-              # git add -A
-              # git commit --allow-empty -m "Deploy to GitHub pages [ci skip]"
-              # git push --force --quiet origin gh-pages > /dev/null 2>&1
-              # cd ..
-              # rm -rf gh-pages-branch
+              set -e
+              remote=$(git config remote.origin.url)
+              if [ ! -d "build" ]
+              then
+                  echo "build folder not found"
+                  exit 1
+              fi
+              git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
+              git config --global user.name "$GH_NAME" > /dev/null 2>&1
+              git init
+              git remote add --fetch origin "$remote"
+              if [! -d "node_modules"]
+              then 
+                echo "not installed yet"
+                npm install
+              fi
+              npm run deploy
               echo "Finished GitHub pages Deployment!"
   deploy-prod:
     <<: *defaults
